# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 12:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_youtube_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='youtube_video',
            old_name='thumnails',
            new_name='thumbnails',
        ),
    ]
