# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20170626_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
